### ISSUE TITLE
Add legend about iER, aER, rER

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/Visualizer#10]
A button somewhere in the UI should load a legend explaining that round things are iERs, square aERs, etc.

**Comment by ElmiraOn** [comment]
Cannot do this, because updating the colours, must happen before creating the HTML file (another restriction because of the one-way communication between the backend and front end we have at the moment).  But I can move it to a side-bar
![image](https://user-images.githubusercontent.com/90576588/206293611-b9cc8d9a-1a5d-4f0b-9604-d7ab7dc9f114.png)

expanding sidebar:
![image](https://user-images.githubusercontent.com/90576588/206293764-260d718d-a77b-47c0-84bb-ebd3b0d722a0.png)



> If possible, move Customization to the bottom (under the visualization window).

**Comment by biltzerpos** [comment]
Probably best to leave Customization as is then, for now.

**Comment by ElmiraOn** [comment]
ok, what about the legend? I can make it expandable but should it be at the top or bottom?

**Comment by ElmiraOn** [comment]
I made a small network for the legend so that when the user changes colour of the entities their colours would also change:
![image](https://user-images.githubusercontent.com/90576588/206306069-60835a84-c767-4c7f-9529-d90a34f71ca2.png)

I noticed that for the relationships, naming them based on their invert relation would make more sense (e.g. e ----> f feels like we are saying e is part of f while it is opposite, but it would make sense to say e has part f)

**Comment by ElmiraOn** [comment]
added the legend. it is in an expandable container under the graph and contains all nodes and relations used. They correspond to the actual node's colour and shape

**Comment by mbaljko** [comment]
Hi Elmira, the legend looks great!  
a couple of pieces of feedback
- can the labels be consistent and spelled out fully so as not not rely solely on acronyms, e.g., activity ER (aER), rubric ER (rER), instructional ER (iER), all labels below or to the left of the symbol
- you can drop the labels a...f, idt they are nec.
- the 'general' label - should this be "non-composite iER"?
- can you disable interactivity in the legend panel? accidental mouse action messes up the legend unrecoverably

**Comment by ElmiraOn** [comment]
No worries, I'm on it :)

**Comment by ElmiraOn** [comment]
I disabled all the possible interactivity however when we resize the browser window the created legend does not resize itself properly  so I activated the navigation buttons to allow users to ability to bring the legend to focus

**Comment by mbaljko** [comment]
just the alignment of the labels in the legend is a bit scuffed - assume you are still working on it tho...

**Comment by ElmiraOn** [comment]
I can use align for node option in js however, it only works with monospace:
![image](https://user-images.githubusercontent.com/90576588/206327745-ccdb9497-19e2-4f0d-9d5a-dbe0e5412436.png)
is that alright?

**Comment by mbaljko** [comment]
perfect!  you should stop now!!! I didn't realize you have a final exam tmr.  thx very much, YOU ARE FAB!!

**Comment by ElmiraOn** [comment]
No problem, I enjoyed working on it :). Should I push to the main or being in development is fine for tomorrow?

**Comment by mbaljko** [comment]
dev is fine for tmr, awesome-o re: legend/customization swap. thx!!!!!!!
