### ISSUE TITLE
Collapsed view

### ISSUE THREAD

**Issue by annisiren** [LePa-YU/Visualizer#5]
Create a view with the atomic ER not in view e.g. only the aER, iER and rER are visible.

**Comment by biltzerpos** [comment]
Good point. What is currently view 2 is essentially this, except the iER is missing. It would be good to add the iER to view 2 so that the graph is connected as well. And rename it to "AIR view" or something. If this can be done within 20 minutes or so, let's go for it, otherwise we should wait for the views from the design team.

**Comment by ElmiraOn** [comment]
it should be possible to add this view in a few minutes since it is simply two relationships out of three that are already implemented. I'll work on tomorow

**Comment by ElmiraOn** [comment]
The AIR view is added, let me know if I should make any changes to it

**Comment by biltzerpos** [comment]
Looks great. Marking this as closed. Make sure to test this view with different data sets.
